# fly.toml app configuration file generated for inventory-karim on 2023-08-24T09:22:44+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "inventory-karim"
primary_region = "mad"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
